baseURL = "http://192.168.1.181/"
#RelativeURLs=true
#CanonifyURLs=true

languageCode = "en-us"
theme = "ramium"

title = "Ramium"
disqusShortname = "rafed123"
googleAnalytics = "googra"

paginate = 1
summaryLength = 45

[params]
    googleSearch = "000151824860492892407:kd5zijxwj6a"
    subtitle = ""
    description = ""
    
[taxonomies]
    tag = "tags"
    series = "series"

#[permalinks] 
#    posts = "/:slug"