baseURL = "https://rafed.github.io/ramium/"
#RelativeURLs=true
#CanonifyURLs=true

languageCode = "en-us"
theme = "ramium"
assetDir = "static"

title = "Ramium"
disqusShortname = "rafed123"
googleAnalytics = "googra"

summaryLength = 35
pluralizeListTitles = false
enableemoji = false

[params]
    description = "A description for the meta tag of the site"
    googleSearch = "000151824860492892407:kd5zijxwj6a"
    math = false #best to enable this in a page
    showDate = false #make false if dont want to show date

    tagsInHome = 6
    sectionsInHome = 5
    paginatePostsPerPage = 5
    paginateTagsPerPage = 4
    paginateSectionsPerPage = 2

[taxonomies]
    tag = "tags"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "This Blog"
        weight = 2
            [[menu.main]]
                parent = "blog"
                name = "All Tags"
                url = "/tags/"
                weight = 1
            [[menu.main]]
                parent = "blog"
                name = "All Sections"
                url = "/sections/"
                weight = 2
            [[menu.main]]
                parent = "blog"
                name = "All Posts"
                url = "/posts/"
                weight = 3
    
    [[menu.main]]
        name = "Author"
        url = "/author/"
        weight = 3

[markup.goldmark.renderer]
    unsafe= true

